name: Publish Release
on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      webclient: ./js
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Web build
        run: |
          npm ci
          npm run build:release
        working-directory: ${{env.webclient}}
      - name: Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install setuptools
        run: python -m pip install --upgrade "setuptools<70" wheel twine
      - name: Release (JS + Python)
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "sebastien.jourdain@kitware.com"
          npm run semantic-release
        working-directory: ${{env.webclient}}
      - name: Publish docs
        if: github.ref == 'refs/heads/master'
        env:
          GIT_PUBLISH_URL: https://${{ secrets.GH_PUBLISH_CREDS }}@github.com/Kitware/wslink.git
        run: npm run doc:publish
        working-directory: ${{env.webclient}}
